name: Publish If Not Exists
description: Publishes a local package if it doesn't already exist on NPM Registry

inputs:
  name:
    description: 'Name of the package to publish'
    required: true

  path:
    description: 'Path to the package to publish'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install JQ
      shell: bash
      run: sudo apt-get install jq
    - name: Login
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
    - name: Publish
      shell: bash
      run: |
        local_version=$(cat ${{ inputs.path }}/package.json | jq -r ".version")
        echo "local version: $local_version"

        package_ref="${{ inputs.name }}@$local_version"
        if npm view $package_ref > /dev/null 2>&1 ; then
          echo "Package $package_ref already published"
          exit 0
        fi

        echo "Publishing version $package_ref"
        cd ${{ inputs.path }} && npm publish --access public
