blank_issues_enabled: false
contact_links:
  - name: Issues when using on premise version of Botpress (Botpress V12 and below)
    url: https://github.com/botpress/v12
    about: If you're experiencing issues when using the on premise version of Botpress, please report the issue on the v12 repo.
  - name: Issues when using Botpress Cloud
    url: https://discord.gg/botpress
    about: If you're experiencing issues when using Botpress Cloud or have any question regarding Botpress Cloud but you're not sure about the nature of the issue, please report the issue on our Discord Server.
