name: Feature Request
description: Propose a new feature
title: '[Feat]: '
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this feature request.\n Keep in mind this repository is meant for Developper focused tools, for public integrations developpement and eventually agent developpement (See [This Repository](https://github.com/botpress/botpress#this-repository))."
  - type: checkboxes
    id: dx-related-confirmation
    attributes:
      label: 'Make sure the issue is related to the API, Client, SDK or CLI of Botpress Cloud or a public integration located in this repository.'
      description: 'If you are using Botpress Cloud, ensure that the feature you want to propose is related to code located in this repository. When in doubt, please report the bug on [our Discord Server](https://discord.gg/botpress).'
      options:
        - label: 'I confirm that the proposed feature is not related to Botpress on premise version (v12 and below)'
          required: true
        - label: 'I confirm that the proposed feature is not related to the Botpress Studio'
          required: true
        - label: 'I confirm that the proposed feature is not related to the Botpress Dashboard'
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 'Description of the feature'
      description: "What is the feature you'd like to see implemented? Make sure to add context or any information that you think might help understand and implement the feature."
