name: Check

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: tilt ci -- --cmd generate
      - run: pnpm run format:check
      - run: pnpm run lint:check
      - run: pnpm run type:check
