name: Deploy Interfaces Production

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force re-deploying interfaces'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy Interfaces
        uses: ./.github/actions/deploy-interfaces
        with:
          environment: 'production'
          force: ${{ github.event.inputs.force == 'true' }}
          token_cloud_ops_account: ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}
          cloud_ops_workspace_id: ${{ secrets.PRODUCTION_CLOUD_OPS_WORKSPACE_ID }}
