name: Deploy Integrations Production

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tilt
        uses: ./.github/actions/setup-tilt
      - name: Deploy Integrations
        uses: ./.github/actions/deploy-integrations
        with:
          environment: 'production'
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          token_cloud_ops_account: ${{ secrets.PRODUCTION_TOKEN_CLOUD_OPS_ACCOUNT }}
          cloud_ops_workspace_id: ${{ secrets.PRODUCTION_CLOUD_OPS_WORKSPACE_ID }}
          gmail_client_id: ${{ secrets.PRODUCTION_GMAIL_CLIENT_ID }}
          gmail_client_secret: ${{ secrets.PRODUCTION_GMAIL_CLIENT_SECRET }}
          gmail_topic_name: ${{ secrets.PRODUCTION_GMAIL_TOPIC_NAME }}
          linear_client_id: ${{ secrets.PRODUCTION_LINEAR_CLIENT_ID }}
          linear_client_secret: ${{ secrets.PRODUCTION_LINEAR_CLIENT_SECRET }}
          linear_webhook_signing_secret: ${{ secrets.PRODUCTION_LINEAR_WEBHOOK_SIGNING_SECRET }}
          slack_client_id: ${{ secrets.PRODUCTION_SLACK_CLIENT_ID }}
          slack_client_secret: ${{ secrets.PRODUCTION_SLACK_CLIENT_SECRET }}
