name: Publish Packages

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tilt
        uses: ./.github/actions/setup-tilt
        with:
          tilt_cmd: 'build-packages'
      - name: Publish Client
        uses: ./.github/actions/publish-if-not-exists
        with:
          name: '@botpress/client'
          path: './packages/client'
          token: '${{ secrets.NPM_ACCESS_TOKEN }}'
      - name: Publish SDK
        uses: ./.github/actions/publish-if-not-exists
        with:
          name: '@botpress/sdk'
          path: './packages/sdk'
          token: '${{ secrets.NPM_ACCESS_TOKEN }}'
      - name: Publish CLI
        uses: ./.github/actions/publish-if-not-exists
        with:
          name: '@botpress/cli'
          path: './packages/cli'
          token: '${{ secrets.NPM_ACCESS_TOKEN }}'
