name: Run Checks

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  run-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Tilt
        uses: ./.github/actions/setup-tilt
      - run: pnpm run format:check
      - run: pnpm run lint:check
      - run: pnpm run type:check
      - run: pnpm run dep:check
      - run: pnpm run test
